#####################################################
#  GNOME 3/4
#####################################################
# swipe:
#   4:
#     up:
#       command: 'xdotool key Ctrl+Super+Down'
#     down:
#       command: 'xdotool key Ctrl+Super+Up'
#     left:
#       command: 'xdotool key Ctrl+Super+Left'
#     right:
#       command: 'xdotool key Ctrl+Super+Right'

#   3:
#     up:
#       command: 'xdotool key Super'
#     down:
#       command: 'xdotool key Super+d'

# pinch:
#   in:
#     command: 'xdotool key Super+a'
#   out:
#      command: 'xdotool key Super'
     
# pinch:
#   in:
#     command: 'xdotool key ctrl+plus'
#   out:
#     command: 'xdotool key ctrl+minus'
    
# threshold:
#   swipe: 0.4
#   pinch: 0.4

# interval:
#   swipe: 0.8
#   pinch: 0.1

#####################################################
# XFCE
#####################################################
swipe:
  3: 
    left: 
      command: 'xdotool key ctrl+alt+Right' # Switch workspace ->
    right: 
      command: 'xdotool key ctrl+alt+Left' # Switch workspace <-
    up: 
      command: 'xdotool key super+d' # Show/Hide desktop
    down: 
      command: 'xdotool key super+d' # Show/Hide desktop
  4:
    left: 
      command: 'xdotool key super+f' # Open File Manager
    right: 
      command: 'xfce4-taskmanager'  # Open XFCE Task Manager
    up: 
      command: 'xdotool key super+t' # Open Terminal
    down:
      command: 'xfce4-popup-whiskermenu' # Open Whisker Menu
pinch:
  in:
    command: 'xdotool key ctrl+plus' # Zoom In
  out:
     command: 'xdotool key ctrl+minus' # Zoom Out

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.1
